### ISSUE TITLE
Issue inputting information

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#10]
# Module 3
#### Step 6 and 7

o	‘Item code’ field will not allow any change.
o	‘Item relation’ field will not allow input.

**Comment by janeteblake** [comment]
I could not repro, were you in USMF company? Did your screen look like this? 
![image](https://user-images.githubusercontent.com/54034556/126384452-1403175e-3b5d-453a-9652-9c629717d17b.png)

**Comment by janeteblake** [comment]
Closing as no response.
