### ISSUE TITLE
 Long Activation Time for Worker in MB-310 Module 1

### ISSUE THREAD

**Issue by KashifKhaan** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#111]
Hi Microsoft,

In the MB-310 Microsoft Dynamics 365 Finance Module 1, activating a worker took an unusually long time, approximately two hours. This delay significantly impacts the workflow and user experience.

Steps to reproduce:

Navigate to the worker activation step in Module 1.
Initiate the worker activation process.
Observe the time taken for the activation to complete.
Expected result: Worker activation should be completed in a reasonable timeframe (a few minutes at most).
Actual result: Worker activation took around two hours.

Please investigate and resolve this issue to improve the efficiency of the lab steps.

please see the screenshot for reference:
![image (6)](https://github.com/MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance/assets/88695658/c391527e-e216-4fe6-8ece-328699acc2bf)

Thank you.

**Comment by janeteblake** [comment]
Thank you so much for reporting this issue! We sincerely appreciate feedback. 

Based on the image provided (thank you!), we assume you mean activating the advanced rule structure, not activating a worker.

We see two ways this might have happened: 1) it appeared to be hung when it actually worked, or 2) the virtual environment was hung.

We believe it was #1, so are adding instructions to the lab on how to monitor the status.

In the unlikely event it was #2, we recommend that you report the issue to your lab hoster.

Please check back Wednesday for updated lab instructions.
