### ISSUE TITLE
Error Posting Journal Entry

### ISSUE THREAD

**Issue by behymerd** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#17]
# Module: 02
#### Step: 10

Link to Instructions:  [https://github.com/MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance/blob/master/Instructions/Labs/MB-310-MOD2_Lab06.md#exercise-6-create-and-use-voucher-templates](url)

Description of issue: While trying to post a Journal entry to the General ledger you get a pop-up saying "Operation canceled: Validating and posting journal".   Had an instructor report this issue and I was able to repro.  Attaching screenshot.

Is there a fix for this?

![image](https://user-images.githubusercontent.com/83354898/127376395-dc696866-77ef-4626-bb9a-8be3f9b36f31.png)

**Comment by janeteblake** [comment]
Can repro. Investigating.

**Comment by janeteblake** [comment]
Thank you for reporting this error, behymerd! We appreciate the time you took to do it.

We have updated Step 9. Could you kindly confirm if it works for you now?
