### ISSUE TITLE
the numbering of the exercises is out of sync with the courseware update of 29 August

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#19]
the numbering of the exercises is out of sync with the courseware update of 29 August  -  it is hard to direct students to the correct exercise without moving back and forwards throughout the exercise -- some exercises do not say which module they are referred to. could this be updated please? 

Many thanks.

**Comment by janeteblake** [comment]
Hi chaast and thank you for your feedback! I've examined it and as far as I can tell, all are aligned. The labs in the screenshot below are at https://microsoftlearning.github.io/MB-310-Microsoft-Dynamics-365-Finance/ . Would you kindly elaborate? Thank you! 
![image](https://user-images.githubusercontent.com/54034556/134201822-8792ab2b-ac20-4d13-bf6f-d9db65f91064.png)

**Comment by janeteblake** [comment]
Will close in one week.

**Comment by chaast** [comment]
He Janet, thank you for coming back to me. Could you please keep this open until 13 October?

I am in the middle of running 12 hour teaching courses and have downtime in the first week of October. The earliest I can look at the again would be week commencing 11 October.

Thank you so much.
Kind regards
Cindy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by janeteblake** [comment]
Yes, that is perfectly fine! 
Janet
