### ISSUE TITLE
MB-310-MOD6_Lab02 & MB-310-MOD6_Lab03.md: Exercises are duplicates

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#22]
# Module: 06
#### Step: 00

Description of issue

The markdown for both of these labs contains an 'exercise 2' in both that are identical.  

Is there intended to be one or the other with different exercise steps?

**Comment by janeteblake** [comment]
Exercise 2 was inadvertently overwritten to Exercise 3. We've restored 3. Thank you very much for bringing this to our attention!
