### ISSUE TITLE
/images directory missing?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#27]
# Module: Multiple
#### Step: Multiple

Description of issue

The new instructions reference images, but there does not appear to be an /images dir present in the repo containing the referenced .png files.  i.e.:

![image](https://user-images.githubusercontent.com/49700217/161441024-348f4d8e-a82b-4b72-82cb-a90097a9b310.png)

**Comment by janeteblake** [comment]
Thank you for your feedback. Images folder created. 
![image](https://user-images.githubusercontent.com/54034556/163004479-429e9208-bd22-461f-a30b-a9ac8d63e253.png)
