### ISSUE TITLE
Missing financial dimension

### ISSUE THREAD

**Issue by Tattedgeek** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#29]
# Module: 08
#### Step: 04

Description of issue

The system throws and error saying that there is a missing financial dimension on the object.

Repro steps:

1.
1.
1
![2022-04-18_18-45-54](https://user-images.githubusercontent.com/31896372/163850363-12ef9a0d-eb31-439d-aef2-be41e47360d7.png)
.

**Comment by janeteblake** [comment]
Can not reproduce. 
![image](https://user-images.githubusercontent.com/54034556/163866665-d4a5338e-e661-4a24-8d2e-7df9cf1b2c7d.png)

**Comment by Tattedgeek** [comment]
Thank you. Re-ran and seems to be ok now.
