### ISSUE TITLE
Import Exchange Rates dialog box issues 

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#4]
# Module: 02

Need additional instructions around what to do when the following dialog box pops up
 
![image](https://user-images.githubusercontent.com/36937661/112418773-da69f800-8d75-11eb-86b5-9e9ba9e65e17.png)

**Comment by AustinP00** [comment]
This issue appears to be addressed prior to Exercise/Module 1 of the instructions - was not able to replicate this issue:

![image](https://user-images.githubusercontent.com/53233868/112565735-0015f200-8db4-11eb-839f-a28aa913647f.png)

**Comment by janeteblake** [comment]
Added note.
