### ISSUE TITLE
Error on making any changes to the interval

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#5]
# Module 2
#### Step 11

On making any changes to the interval, the following error notifications occur. 

![image](https://user-images.githubusercontent.com/36937661/112420076-48afba00-8d78-11eb-9519-696507ca0446.png)

**Comment by AustinP00** [comment]
able to replicate issue - will  be in repro write up

**Comment by janeteblake** [comment]
Could not replicate. Followed the initial instructions through "Create a date interval for month of August" and saved. Then made several changes. No errors or warnings. Sounds like you may not have been in USMF company?

**Comment by janeteblake** [comment]
Closing as no response.
