### ISSUE TITLE
Error if the user does not switch to the USMF Environment

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#6]
# Module 2
### Step 3

No journal names present

![image](https://user-images.githubusercontent.com/36937661/112420701-62053600-8d79-11eb-93e2-0fd53776b6be.png)

**Comment by AustinP00** [comment]
adding to repro write up - no journal entry for selection

**Comment by janeteblake** [comment]
Added company navigation in step 1. Thank you.
