### ISSUE TITLE
Debit and Credit account fields will not allow any input.

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#7]
# Module 2
#### Steps 5 and 6

Debit and Credit account fields will not allow any input.

![image](https://user-images.githubusercontent.com/36937661/112421051-1737ee00-8d7a-11eb-869c-5bf9dfd81370.png)

**Comment by janeteblake** [comment]
1. I could not replicate. See screenshot, it worked for me. I suspect you may not have been in company USMF. I am now in USMF, so you may have corrected this before I looked at it?
2. I notice that the options for Voucher have changed slightly. I will change the option for step 7 to "New voucher for each accrual transaction date".

![image](https://user-images.githubusercontent.com/54034556/126379939-74a95e33-9a3f-4192-b335-a84764e3106c.png)

**Comment by janeteblake** [comment]
Closing as no response.
