### ISSUE TITLE
Types field is absent.

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#8]
# Module 2
#### Step 5

Types field is absent

![image](https://user-images.githubusercontent.com/36937661/112421177-52d2b800-8d7a-11eb-902d-ac4be6f1e7ee.png)

**Comment by janeteblake** [comment]
I agree the phrasing here is unclear. I will clarify step 5 to say that you should be "navigating to" the Type FastTab (section).
![image](https://user-images.githubusercontent.com/54034556/126381516-07efc58a-b973-4156-b4dd-62418318bc47.png)

**Comment by janeteblake** [comment]
Clarified and closed
