### ISSUE TITLE
Account details are required to be input in the BusinessUnit and Department fields

### ISSUE THREAD

**Issue by benjames007** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#9]
# Module 2
### Step 18

Further account details are required to be input in the BusinessUnit and Department fields

![image](https://user-images.githubusercontent.com/36937661/112421539-f3c17300-8d7a-11eb-950b-950609e6d6dc.png)

**Comment by AustinP00** [comment]
can be effect of ex 4 creating fiscal calendar error

**Comment by janeteblake** [comment]
Could not repro - I navigated out of the field after choosing simply 110110. I agree it sounds like an error elsewhere.
![image](https://user-images.githubusercontent.com/54034556/126382589-d154b6b8-9314-433f-876b-0309b61bdd67.png)

**Comment by janeteblake** [comment]
You are correct, I have corrected step 18 to add a department of 022.

**Comment by janeteblake** [comment]
Corrected & closing.
