### ISSUE TITLE
Module 6, lab 1, task 3, step 3, unable to see the new temporary credit limit

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-310-Microsoft-Dynamics-365-Finance#93]
# Module: 6
#### Step: 3

Description of issue
All steps followed correctly and temporary credit limit was posted, but i can't see it on the customer record...

for this to work, you would have to pick in a date in the future (task 2, step 10) -- then it works correctly.

Would you please be able to update the instructions.

![image](https://user-images.githubusercontent.com/89986870/177725148-1e5d0513-8c51-496a-95f5-a914696875ac.png)

![image](https://user-images.githubusercontent.com/89986870/177725899-4b050885-f006-4c12-aedd-2e55c00e66b8.png)

**Comment by janeteblake** [comment]
Thank you very much for reporting this issue. We have corrected the text. It is reflected in GitHub now and will be reflected in the hosted virtual machines tomorrow. We appreciate the time you took!
